on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Get version from package.json
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Package Extension
        run: npx vsce package

      - name: Upload VSIX as artifact
        uses: actions/upload-artifact@v3
        with:
          name: "monochromator-${{ env.VERSION }}"
          path: "*.vsix"
